# Generated by Django 5.0.2 on 2024-03-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dog_breed', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=200, unique=True)),
                ('vet_id', models.IntegerField(max_length=200)),
                ('date', models.DateField()),
                ('phone', models.IntegerField(max_length=10)),
                ('time', models.TimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
