# Generated by Django 5.0.2 on 2024-03-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0003_alter_appointment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
