# Generated by Django 4.2.7 on 2024-03-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0004_appointment_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(max_length=200),
        ),
    ]
