# Generated by Django 5.0.2 on 2024-04-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
